[
  {
    "level": 1,
    "xp_to_reach": 0,
    "xp_from_previous": 0,
    "title": "First Stroke",
    "unlocks": ["Basic Brush", "8 Starter Colors", "Welcome Confetti"],
    "milestone": false,
    "celebration": "Gentle rainbow confetti + soft chime",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.0
  },
  {
    "level": 2,
    "xp_to_reach": 100,
    "xp_from_previous": 100,
    "title": "Color Curious",
    "unlocks": ["Eraser Tool", "Undo Button", "5 New Colors"],
    "milestone": false,
    "celebration": "Sparkle burst + gentle ding",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.0
  },
  {
    "level": 3,
    "xp_to_reach": 250,
    "xp_from_previous": 150,
    "title": "Brush Explorer",
    "unlocks": ["Brush Size Control", "Opacity Slider", "10 Art Gems"],
    "milestone": false,
    "celebration": "Color swirl + brush sound",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.0
  },
  {
    "level": 4,
    "xp_to_reach": 450,
    "xp_from_previous": 200,
    "title": "Canvas Wanderer",
    "unlocks": ["Clear Canvas", "Surprise Me Button", "Pastel Color Pack"],
    "milestone": false,
    "celebration": "Pastel confetti + wind chime",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.0
  },
  {
    "level": 5,
    "xp_to_reach": 700,
    "xp_from_previous": 250,
    "title": "Rainbow Apprentice",
    "unlocks": ["Rainbow Brush", "Sparkle Effect", "Nature Realm", "25 Art Gems", "First Achievement Badge"],
    "milestone": true,
    "celebration": "Rainbow explosion + magical chime sequence",
    "realm_unlocked": "Nature Realm",
    "daily_reward_multiplier": 1.2
  },
  {
    "level": 6,
    "xp_to_reach": 1000,
    "xp_from_previous": 300,
    "title": "Glow Seeker",
    "unlocks": ["Glow Effect", "Warm Color Pack", "Daily Quest Unlock"],
    "milestone": false,
    "celebration": "Golden glow + warm hum",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.2
  },
  {
    "level": 7,
    "xp_to_reach": 1350,
    "xp_from_previous": 350,
    "title": "Pattern Maker",
    "unlocks": ["Pattern Fill Tool", "Cool Color Pack", "15 Art Gems"],
    "milestone": false,
    "celebration": "Geometric burst + tech beep",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.2
  },
  {
    "level": 8,
    "xp_to_reach": 1750,
    "xp_from_previous": 400,
    "title": "Symmetry Student",
    "unlocks": ["Mirror Mode", "Symmetry Toggle", "Metallic Color Pack"],
    "milestone": false,
    "celebration": "Mirror flash + crystal ping",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.2
  },
  {
    "level": 9,
    "xp_to_reach": 2200,
    "xp_from_previous": 450,
    "title": "Stamp Collector",
    "unlocks": ["Basic Stamp Tool", "Emoji Pack 1", "20 Art Gems"],
    "milestone": false,
    "celebration": "Stamp impression + pop sound",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.2
  },
  {
    "level": 10,
    "xp_to_reach": 2700,
    "xp_from_previous": 500,
    "title": "Neon Dreamer",
    "unlocks": ["Neon Glow Brush", "Cyberpunk Night Realm", "Electric Particle Trail", "50 Art Gems", "Neon Avatar Frame"],
    "milestone": true,
    "celebration": "Full-screen electric explosion + synth whoosh",
    "realm_unlocked": "Cyberpunk Night",
    "daily_reward_multiplier": 1.5
  },
  {
    "level": 11,
    "xp_to_reach": 3250,
    "xp_from_previous": 550,
    "title": "Watercolor Novice",
    "unlocks": ["Watercolor Brush", "Soft Blend Mode", "Earth Tone Pack"],
    "milestone": false,
    "celebration": "Watercolor splash + gentle flow",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.5
  },
  {
    "level": 12,
    "xp_to_reach": 3850,
    "xp_from_previous": 600,
    "title": "Particle Pioneer",
    "unlocks": ["Particle Explosion Effect", "Gravity Paint", "25 Art Gems"],
    "milestone": false,
    "celebration": "Particle shower + whoosh",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.5
  },
  {
    "level": 13,
    "xp_to_reach": 4500,
    "xp_from_previous": 650,
    "title": "Smudge Artist",
    "unlocks": ["Smudge Tool", "Finger Paint Mode", "Organic Color Pack"],
    "milestone": false,
    "celebration": "Smooth swirl + finger tap",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.5
  },
  {
    "level": 14,
    "xp_to_reach": 5200,
    "xp_from_previous": 700,
    "title": "Trail Blazer",
    "unlocks": ["Sparkle Trail Effect", "Motion Blur", "30 Art Gems"],
    "milestone": false,
    "celebration": "Glittering trail + magic sparkle",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.5
  },
  {
    "level": 15,
    "xp_to_reach": 5950,
    "xp_from_previous": 750,
    "title": "Ocean Painter",
    "unlocks": ["Ocean Wave Brush", "Underwater Realm", "Bubble Particle Effect", "Aqua Color Palette", "75 Art Gems"],
    "milestone": true,
    "celebration": "Ocean wave animation + whale song",
    "realm_unlocked": "Underwater Realm",
    "daily_reward_multiplier": 1.8
  },
  {
    "level": 16,
    "xp_to_reach": 6750,
    "xp_from_previous": 800,
    "title": "Kaleidoscope Keeper",
    "unlocks": ["Kaleidoscope Mode x4", "Prism Effect", "Crystal Color Pack"],
    "milestone": false,
    "celebration": "Kaleidoscope spin + crystal chime",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.8
  },
  {
    "level": 17,
    "xp_to_reach": 7600,
    "xp_from_previous": 850,
    "title": "Fire Dancer",
    "unlocks": ["Fire Brush", "Flame Particle Trail", "35 Art Gems"],
    "milestone": false,
    "celebration": "Fire burst + crackling sound",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.8
  },
  {
    "level": 18,
    "xp_to_reach": 8500,
    "xp_from_previous": 900,
    "title": "Ice Sculptor",
    "unlocks": ["Frost Brush", "Ice Crystal Effect", "Winter Color Pack"],
    "milestone": false,
    "celebration": "Ice crystal formation + wind",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.8
  },
  {
    "level": 19,
    "xp_to_reach": 9450,
    "xp_from_previous": 950,
    "title": "Lightning Wielder",
    "unlocks": ["Lightning Brush", "Electric Zap Effect", "40 Art Gems"],
    "milestone": false,
    "celebration": "Lightning strike + thunder",
    "realm_unlocked": null,
    "daily_reward_multiplier": 1.8
  },
  {
    "level": 20,
    "xp_to_reach": 10450,
    "xp_from_previous": 1000,
    "title": "Space Explorer",
    "unlocks": ["Galaxy Brush", "Space Realm", "Nebula Particle Effect", "Cosmic Color Palette", "100 Art Gems", "Space Avatar Frame"],
    "milestone": true,
    "celebration": "Galaxy swirl + cosmic ambience",
    "realm_unlocked": "Space Realm",
    "daily_reward_multiplier": 2.0
  },
  {
    "level": 21,
    "xp_to_reach": 11500,
    "xp_from_previous": 1050,
    "title": "Prism Master",
    "unlocks": ["Prism Brush", "Light Refraction Effect", "Spectrum Color Pack"],
    "milestone": false,
    "celebration": "Prism light split + harmonic tone",
    "realm_unlocked": null,
    "daily_reward_multiplier": 2.0
  },
  {
    "level": 22,
    "xp_to_reach": 12600,
    "xp_from_previous": 1100,
    "title": "Wind Painter",
    "unlocks": ["Wind Brush", "Leaf Scatter Effect", "45 Art Gems"],
    "milestone": false,
    "celebration": "Wind gust + rustling leaves",
    "realm_unlocked": null,
    "daily_reward_multiplier": 2.0
  },
  {
    "level": 23,
    "xp_to_reach": 13750,
    "xp_from_previous": 1150,
    "title": "Crystal Weaver",
    "unlocks": ["Crystal Brush", "Gem Sparkle Effect", "Jewel Color Pack"],
    "milestone": false,
    "celebration": "Crystal formation + bell chime",
    "realm_unlocked": null,
    "daily_reward_multiplier": 2.0
  },
  {
    "level": 24,
    "xp_to_reach": 14950,
    "xp_from_previous": 1200,
    "title": "Shadow Dancer",
    "unlocks": ["Shadow Brush", "Darkness Effect", "50 Art Gems"],
    "milestone": false,
    "celebration": "Shadow wave + mysterious whisper",
    "realm_unlocked": null,
    "daily_reward_multiplier": 2.0
  },
  {
    "level": 25,
    "xp_to_reach": 16200,
    "xp_from_previous": 1250,
    "title": "Legendary Chromancer",
    "unlocks": ["Legendary Aurora Brush", "Candy Kingdom Realm", "Kaleidoscope x8 Mode", "Mythic Stamp Pack", "Double XP Power-up", "150 Art Gems"],
    "milestone": true,
    "celebration": "Legendary aura + heavenly choir",
    "realm_unlocked": "Candy Kingdom",
    "daily_reward_multiplier": 2.5
  },
  {
    "level": 26,
    "xp_to_reach": 17500,
    "xp_from_previous": 1300,
    "title": "Plasma Wielder",
    "unlocks": ["Plasma Brush", "Energy Field Effect", "Electric Color Pack"],
    "milestone": false,
    "celebration": "Plasma burst + energy hum",
    "realm_unlocked": null,
    "daily_reward_multiplier": 2.5
  },
  {
    "level": 27,
    "xp_to_reach": 18850,
    "xp_from_previous": 1350,
    "title": "Void Walker",
    "unlocks": ["Void Brush", "Black Hole Effect", "55 Art Gems"],
    "milestone": false,
    "celebration": "Void portal + deep resonance",
    "realm_unlocked": null,
    "daily_reward_multiplier": 2.5
  },
  {
    "level": 28,
    "xp_to_reach": 20250,
    "xp_from_previous": 1400,
    "title": "Time Bender",
    "unlocks": ["Time Ripple Brush", "Temporal Effect", "Chronos Color Pack"],
    "milestone": false,
    "celebration": "Time distortion + clock ticking",
    "realm_unlocked": null,
    "daily_reward_multiplier": 2.5
  },
  {
    "level": 29,
    "xp_to_reach": 21700,
    "xp_from_previous": 1450,
    "title": "Dream Weaver",
    "unlocks": ["Dream Brush", "Ethereal Glow Effect", "60 Art Gems"],
    "milestone": false,
    "celebration": "Dream mist + lullaby melody",
    "realm_unlocked": null,
    "daily_reward_multiplier": 2.5
  },
  {
    "level": 30,
    "xp_to_reach": 23200,
    "xp_from_previous": 1500,
    "title": "Celestial Artist",
    "unlocks": ["Celestial Brush", "Heaven Realm", "Angel Wing Effect", "Divine Color Palette", "Infinite Undo Power-up", "200 Art Gems"],
    "milestone": true,
    "celebration": "Heavenly light + angelic chorus",
    "realm_unlocked": "Heaven Realm",
    "daily_reward_multiplier": 3.0
  },
  {
    "level": 31,
    "xp_to_reach": 24750,
    "xp_from_previous": 1550,
    "title": "Quantum Painter",
    "unlocks": ["Quantum Brush", "Particle Wave Effect", "Quantum Color Pack"],
    "milestone": false,
    "celebration": "Quantum fluctuation + sci-fi beep",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.0
  },
  {
    "level": 32,
    "xp_to_reach": 26350,
    "xp_from_previous": 1600,
    "title": "Phoenix Rising",
    "unlocks": ["Phoenix Brush", "Rebirth Effect", "65 Art Gems"],
    "milestone": false,
    "celebration": "Phoenix cry + fire rebirth",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.0
  },
  {
    "level": 33,
    "xp_to_reach": 28000,
    "xp_from_previous": 1650,
    "title": "Dragon Tamer",
    "unlocks": ["Dragon Breath Brush", "Scale Texture Effect", "Dragon Color Pack"],
    "milestone": false,
    "celebration": "Dragon roar + flame breath",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.0
  },
  {
    "level": 34,
    "xp_to_reach": 29700,
    "xp_from_previous": 1700,
    "title": "Unicorn Whisperer",
    "unlocks": ["Unicorn Horn Brush", "Magic Sparkle Effect", "70 Art Gems"],
    "milestone": false,
    "celebration": "Unicorn neigh + magical sparkles",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.0
  },
  {
    "level": 35,
    "xp_to_reach": 31450,
    "xp_from_previous": 1750,
    "title": "Elemental Master",
    "unlocks": ["All Elements Brush", "Elemental Fusion Effect", "Elemental Color Pack", "Circle Canvas Shape", "75 Art Gems"],
    "milestone": true,
    "celebration": "Elemental convergence + nature symphony",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.2
  },
  {
    "level": 36,
    "xp_to_reach": 33250,
    "xp_from_previous": 1800,
    "title": "Gravity Defier",
    "unlocks": ["Anti-Gravity Brush", "Floating Effect", "Weightless Color Pack"],
    "milestone": false,
    "celebration": "Gravity shift + floating sound",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.2
  },
  {
    "level": 37,
    "xp_to_reach": 35100,
    "xp_from_previous": 1850,
    "title": "Dimension Walker",
    "unlocks": ["Portal Brush", "Dimensional Rift Effect", "80 Art Gems"],
    "milestone": false,
    "celebration": "Portal opening + dimensional hum",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.2
  },
  {
    "level": 38,
    "xp_to_reach": 37000,
    "xp_from_previous": 1900,
    "title": "Energy Conductor",
    "unlocks": ["Energy Beam Brush", "Power Surge Effect", "Energy Color Pack"],
    "milestone": false,
    "celebration": "Energy discharge + electric buzz",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.2
  },
  {
    "level": 39,
    "xp_to_reach": 38950,
    "xp_from_previous": 1950,
    "title": "Soul Artist",
    "unlocks": ["Soul Brush", "Spirit Glow Effect", "85 Art Gems"],
    "milestone": false,
    "celebration": "Soul resonance + ethereal hum",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.2
  },
  {
    "level": 40,
    "xp_to_reach": 40950,
    "xp_from_previous": 2000,
    "title": "Mythic Realm Walker",
    "unlocks": ["Mythic Brush Set", "Enchanted Forest Realm", "Fairy Dust Effect", "Mythical Color Palette", "Heart Canvas Shape", "300 Art Gems"],
    "milestone": true,
    "celebration": "Mythic transformation + forest magic",
    "realm_unlocked": "Enchanted Forest",
    "daily_reward_multiplier": 3.5
  },
  {
    "level": 41,
    "xp_to_reach": 43000,
    "xp_from_previous": 2050,
    "title": "Cosmic Weaver",
    "unlocks": ["Cosmic Thread Brush", "Star Formation Effect", "Cosmic Color Pack"],
    "milestone": false,
    "celebration": "Cosmic weaving + stellar birth",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.5
  },
  {
    "level": 42,
    "xp_to_reach": 45100,
    "xp_from_previous": 2100,
    "title": "Reality Shaper",
    "unlocks": ["Reality Brush", "Existence Warp Effect", "90 Art Gems"],
    "milestone": false,
    "celebration": "Reality bend + existence hum",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.5
  },
  {
    "level": 43,
    "xp_to_reach": 47250,
    "xp_from_previous": 2150,
    "title": "Infinity Painter",
    "unlocks": ["Infinity Brush", "Endless Loop Effect", "Infinite Color Pack"],
    "milestone": false,
    "celebration": "Infinity symbol + eternal tone",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.5
  },
  {
    "level": 44,
    "xp_to_reach": 49450,
    "xp_from_previous": 2200,
    "title": "Chaos Controller",
    "unlocks": ["Chaos Brush", "Random Burst Effect", "95 Art Gems"],
    "milestone": false,
    "celebration": "Chaos explosion + random sounds",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.5
  },
  {
    "level": 45,
    "xp_to_reach": 51700,
    "xp_from_previous": 2250,
    "title": "Harmony Master",
    "unlocks": ["Harmony Brush", "Perfect Balance Effect", "Zen Color Pack", "Hexagon Canvas Shape", "100 Art Gems"],
    "milestone": true,
    "celebration": "Perfect harmony + zen bells",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.8
  },
  {
    "level": 46,
    "xp_to_reach": 54000,
    "xp_from_previous": 2300,
    "title": "Astral Projector",
    "unlocks": ["Astral Brush", "Out-of-Body Effect", "Astral Color Pack"],
    "milestone": false,
    "celebration": "Astral projection + ethereal whoosh",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.8
  },
  {
    "level": 47,
    "xp_to_reach": 56350,
    "xp_from_previous": 2350,
    "title": "Mind Bender",
    "unlocks": ["Psychic Brush", "Telepathic Effect", "105 Art Gems"],
    "milestone": false,
    "celebration": "Mind wave + psychic pulse",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.8
  },
  {
    "level": 48,
    "xp_to_reach": 58750,
    "xp_from_previous": 2400,
    "title": "Dimension Creator",
    "unlocks": ["Creator Brush", "Universe Birth Effect", "Creator Color Pack"],
    "milestone": false,
    "celebration": "Big bang + universe creation",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.8
  },
  {
    "level": 49,
    "xp_to_reach": 61200,
    "xp_from_previous": 2450,
    "title": "Eternal Artist",
    "unlocks": ["Eternal Brush", "Timeless Effect", "110 Art Gems"],
    "milestone": false,
    "celebration": "Eternal glow + timeless echo",
    "realm_unlocked": null,
    "daily_reward_multiplier": 3.8
  },
  {
    "level": 50,
    "xp_to_reach": 63700,
    "xp_from_previous": 2500,
    "title": "Mythic Chromancer Supreme",
    "unlocks": ["Supreme Aurora Brush", "Aurora Borealis Realm", "Kaleidoscope x12 Mode", "Legendary Stamp Collection", "Permanent 2x XP Boost", "500 Art Gems"],
    "milestone": true,
    "celebration": "Heavenly choir + galaxy swirl animation + golden rain",
    "realm_unlocked": "Aurora Borealis",
    "daily_reward_multiplier": 4.0
  },
  {
    "level": 51,
    "xp_to_reach": 66250,
    "xp_from_previous": 2550,
    "title": "Galactic Overlord",
    "unlocks": ["Galaxy Control Brush", "Supernova Effect", "Galactic Color Pack"],
    "milestone": false,
    "celebration": "Galactic explosion + cosmic roar",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.0
  },
  {
    "level": 52,
    "xp_to_reach": 68850,
    "xp_from_previous": 2600,
    "title": "Multiverse Guardian",
    "unlocks": ["Multiverse Brush", "Reality Split Effect", "115 Art Gems"],
    "milestone": false,
    "celebration": "Multiverse split + guardian call",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.0
  },
  {
    "level": 53,
    "xp_to_reach": 71500,
    "xp_from_previous": 2650,
    "title": "Omnipotent Creator",
    "unlocks": ["Omnipotent Brush", "Divine Creation Effect", "Divine Color Pack"],
    "milestone": false,
    "celebration": "Divine light + creation hymn",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.0
  },
  {
    "level": 54,
    "xp_to_reach": 74200,
    "xp_from_previous": 2700,
    "title": "Transcendent Being",
    "unlocks": ["Transcendent Brush", "Ascension Effect", "120 Art Gems"],
    "milestone": false,
    "celebration": "Transcendence + ascending tone",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.0
  },
  {
    "level": 55,
    "xp_to_reach": 76950,
    "xp_from_previous": 2750,
    "title": "Universal Architect",
    "unlocks": ["Architect Brush", "Blueprint Effect", "Star Canvas Shape", "Architect Color Pack", "125 Art Gems"],
    "milestone": true,
    "celebration": "Blueprint unfold + architect theme",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.2
  },
  {
    "level": 56,
    "xp_to_reach": 79750,
    "xp_from_previous": 2800,
    "title": "Quantum Overlord",
    "unlocks": ["Quantum Control Brush", "Probability Wave Effect", "Quantum Color Pack"],
    "milestone": false,
    "celebration": "Quantum collapse + probability hum",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.2
  },
  {
    "level": 57,
    "xp_to_reach": 82600,
    "xp_from_previous": 2850,
    "title": "Void Emperor",
    "unlocks": ["Void Control Brush", "Nothingness Effect", "130 Art Gems"],
    "milestone": false,
    "celebration": "Void dominion + emperor decree",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.2
  },
  {
    "level": 58,
    "xp_to_reach": 85500,
    "xp_from_previous": 2900,
    "title": "Time Lord",
    "unlocks": ["Time Control Brush", "Temporal Mastery Effect", "Temporal Color Pack"],
    "milestone": false,
    "celebration": "Time mastery + temporal bells",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.2
  },
  {
    "level": 59,
    "xp_to_reach": 88450,
    "xp_from_previous": 2950,
    "title": "Reality Emperor",
    "unlocks": ["Reality Control Brush", "Existence Command Effect", "135 Art Gems"],
    "milestone": false,
    "celebration": "Reality command + imperial fanfare",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.2
  },
  {
    "level": 60,
    "xp_to_reach": 91450,
    "xp_from_previous": 3000,
    "title": "Celestial Emperor",
    "unlocks": ["Celestial Command Brush", "Divine Realm", "Heaven's Gate Effect", "Imperial Color Palette", "Diamond Canvas Shape", "600 Art Gems"],
    "milestone": true,
    "celebration": "Imperial coronation + celestial fanfare",
    "realm_unlocked": "Divine Realm",
    "daily_reward_multiplier": 4.5
  },
  {
    "level": 61,
    "xp_to_reach": 94500,
    "xp_from_previous": 3050,
    "title": "Cosmic Deity",
    "unlocks": ["Deity Brush", "Divine Intervention Effect", "Deity Color Pack"],
    "milestone": false,
    "celebration": "Divine ascension + deity chorus",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.5
  },
  {
    "level": 62,
    "xp_to_reach": 97600,
    "xp_from_previous": 3100,
    "title": "Omniversal Ruler",
    "unlocks": ["Omniverse Brush", "Universal Command Effect", "140 Art Gems"],
    "milestone": false,
    "celebration": "Omniversal rule + cosmic decree",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.5
  },
  {
    "level": 63,
    "xp_to_reach": 100750,
    "xp_from_previous": 3150,
    "title": "Infinite Sovereign",
    "unlocks": ["Infinite Power Brush", "Boundless Effect", "Infinite Color Pack"],
    "milestone": false,
    "celebration": "Infinite power + boundless echo",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.5
  },
  {
    "level": 64,
    "xp_to_reach": 103950,
    "xp_from_previous": 3200,
    "title": "Eternal Monarch",
    "unlocks": ["Eternal Rule Brush", "Everlasting Effect", "145 Art Gems"],
    "milestone": false,
    "celebration": "Eternal reign + monarch anthem",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.5
  },
  {
    "level": 65,
    "xp_to_reach": 107200,
    "xp_from_previous": 3250,
    "title": "Primordial Force",
    "unlocks": ["Primordial Brush", "Origin Effect", "Primordial Color Pack", "Spiral Canvas Shape", "150 Art Gems"],
    "milestone": true,
    "celebration": "Primordial awakening + origin song",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.8
  },
  {
    "level": 66,
    "xp_to_reach": 110500,
    "xp_from_previous": 3300,
    "title": "Abstract Overlord",
    "unlocks": ["Abstract Control Brush", "Conceptual Effect", "Abstract Color Pack"],
    "milestone": false,
    "celebration": "Abstract dominion + conceptual hum",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.8
  },
  {
    "level": 67,
    "xp_to_reach": 113850,
    "xp_from_previous": 3350,
    "title": "Dimensional God",
    "unlocks": ["God Mode Brush", "Divine Wrath Effect", "155 Art Gems"],
    "milestone": false,
    "celebration": "Divine wrath + godly thunder",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.8
  },
  {
    "level": 68,
    "xp_to_reach": 117250,
    "xp_from_previous": 3400,
    "title": "Conceptual Being",
    "unlocks": ["Concept Brush", "Idea Manifestation Effect", "Conceptual Color Pack"],
    "milestone": false,
    "celebration": "Idea birth + conceptual chime",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.8
  },
  {
    "level": 69,
    "xp_to_reach": 120700,
    "xp_from_previous": 3450,
    "title": "Metaphysical Master",
    "unlocks": ["Metaphysical Brush", "Beyond Reality Effect", "160 Art Gems"],
    "milestone": false,
    "celebration": "Metaphysical shift + beyond sound",
    "realm_unlocked": null,
    "daily_reward_multiplier": 4.8
  },
  {
    "level": 70,
    "xp_to_reach": 124200,
    "xp_from_previous": 3500,
    "title": "Transcendental Deity",
    "unlocks": ["Transcendental Brush", "Nirvana Realm", "Enlightenment Effect", "Transcendent Color Palette", "Lotus Canvas Shape", "700 Art Gems"],
    "milestone": true,
    "celebration": "Enlightenment + transcendental bells",
    "realm_unlocked": "Nirvana Realm",
    "daily_reward_multiplier": 5.0
  },
  {
    "level": 71,
    "xp_to_reach": 127750,
    "xp_from_previous": 3550,
    "title": "Absolute Ruler",
    "unlocks": ["Absolute Power Brush", "Total Control Effect", "Absolute Color Pack"],
    "milestone": false,
    "celebration": "Absolute power + ruler fanfare",
    "realm_unlocked": null,
    "daily_reward_multiplier": 5.0
  },
  {
    "level": 72,
    "xp_to_reach": 131350,
    "xp_from_previous": 3600,
    "title": "Supreme Entity",
    "unlocks": ["Supreme Brush", "Ultimate Authority Effect", "165 Art Gems"],
    "milestone": false,
    "celebration": "Supreme authority + entity hum",
    "realm_unlocked": null,
    "daily_reward_multiplier": 5.0
  },
  {
    "level": 73,
    "xp_to_reach": 135000,
    "xp_from_previous": 3650,
    "title": "Perfect Being",
    "unlocks": ["Perfection Brush", "Flawless Effect", "Perfect Color Pack"],
    "milestone": false,
    "celebration": "Perfection achieved + flawless tone",
    "realm_unlocked": null,
    "daily_reward_multiplier": 5.0
  },
  {
    "level": 74,
    "xp_to_reach": 138700,
    "xp_from_previous": 3700,
    "title": "Ultimate Creator",
    "unlocks": ["Ultimate Creation Brush", "Genesis Effect", "170 Art Gems"],
    "milestone": false,
    "celebration": "Ultimate genesis + creation symphony",
    "realm_unlocked": null,
    "daily_reward_multiplier": 5.0
  },
  {
    "level": 75,
    "xp_to_reach": 142450,
    "xp_from_previous": 3750,
    "title": "Legendary Chromatic Overlord",
    "unlocks": ["Chromatic Dominion Brush", "Prismatic Realm", "Spectrum Mastery Effect", "Legendary Avatar Crown", "Infinite Canvas Power-up", "1000 Art Gems"],
    "milestone": true,
    "celebration": "Chromatic dominion + legendary coronation",
    "realm_unlocked": "Prismatic Realm",
    "daily_reward_multiplier": 6.0
  },
  {
    "level": 76,
    "xp_to_reach": 146250,
    "xp_from_previous": 3800,
    "title": "Omniscient Artist",
    "unlocks": ["All-Knowing Brush", "Omniscience Effect", "Wisdom Color Pack"],
    "milestone": false,
    "celebration": "Omniscience + all-knowing hum",
    "realm_unlocked": null,
    "daily_reward_multiplier": 6.0
  },
  {
    "level": 77,
    "xp_to_reach": 150100,
    "xp_from_previous": 3850,
    "title": "Omnipresent Force",
    "unlocks": ["Everywhere Brush", "Omnipresence Effect", "175 Art Gems"],
    "milestone": false,
    "celebration": "Omnipresence + everywhere echo",
    "realm_unlocked": null,
    "daily_reward_multiplier": 6.0
  },
  {
    "level": 78,
    "xp_to_reach": 154000,
    "xp_from_previous": 3900,
    "title": "Omnipotent Master",
    "unlocks": ["All-Powerful Brush", "Omnipotence Effect", "Power Color Pack"],
    "milestone": false,
    "celebration": "Omnipotence + all-powerful roar",
    "realm_unlocked": null,
    "daily_reward_multiplier": 6.0
  },
  {
    "level": 79,
    "xp_to_reach": 157950,
    "xp_from_previous": 3950,
    "title": "Beyond Existence",
    "unlocks": ["Beyond Brush", "Transcendence Effect", "180 Art Gems"],
    "milestone": false,
    "celebration": "Beyond existence + transcendent void",
    "realm_unlocked": null,
    "daily_reward_multiplier": 6.0
  },
  {
    "level": 80,
    "xp_to_reach": 161950,
    "xp_from_previous": 4000,
    "title": "Infinite Possibility",
    "unlocks": ["Possibility Brush", "Quantum Realm", "Infinite Potential Effect", "Possibility Color Palette", "Infinity Canvas Shape", "800 Art Gems"],
    "milestone": true,
    "celebration": "Infinite possibilities + quantum symphony",
    "realm_unlocked": "Quantum Realm",
    "daily_reward_multiplier": 6.5
  },
  {
    "level": 81,
    "xp_to_reach": 166000,
    "xp_from_previous": 4050,
    "title": "Paradox Resolver",
    "unlocks": ["Paradox Brush", "Contradiction Effect", "Paradox Color Pack"],
    "milestone": false,
    "celebration": "Paradox resolution + contradiction harmony",
    "realm_unlocked": null,
    "daily_reward_multiplier": 6.5
  },
  {
    "level": 82,
    "xp_to_reach": 170100,
    "xp_from_previous": 4100,
    "title": "Logic Transcender",
    "unlocks": ["Illogical Brush", "Impossibility Effect", "185 Art Gems"],
    "milestone": false,
    "celebration": "Logic transcendence + impossible sound",
    "realm_unlocked": null,
    "daily_reward_multiplier": 6.5
  },
  {
    "level": 83,
    "xp_to_reach": 174250,
    "xp_from_previous": 4150,
    "title": "Concept Destroyer",
    "unlocks": ["Destruction Brush", "Concept Annihilation Effect", "Void Color Pack"],
    "milestone": false,
    "celebration": "Concept destruction + annihilation wave",
    "realm_unlocked": null,
    "daily_reward_multiplier": 6.5
  },
  {
    "level": 84,
    "xp_to_reach": 178450,
    "xp_from_previous": 4200,
    "title": "Reality Eraser",
    "unlocks": ["Erasure Brush", "Reality Deletion Effect", "190 Art Gems"],
    "milestone": false,
    "celebration": "Reality erasure + deletion silence",
    "realm_unlocked": null,
    "daily_reward_multiplier": 6.5
  },
  {
    "level": 85,
    "xp_to_reach": 182700,
    "xp_from_previous": 4250,
    "title": "Existence Rewriter",
    "unlocks": ["Rewrite Brush", "Existence Edit Effect", "Rewrite Color Pack", "Fractal Canvas Shape", "195 Art Gems"],
    "milestone": true,
    "celebration": "Existence rewrite + reality edit sound",
    "realm_unlocked": null,
    "daily_reward_multiplier": 7.0
  },
  {
    "level": 86,
    "xp_to_reach": 187000,
    "xp_from_previous": 4300,
    "title": "Narrative Controller",
    "unlocks": ["Story Brush", "Plot Control Effect", "Narrative Color Pack"],
    "milestone": false,
    "celebration": "Narrative control + story unfold",
    "realm_unlocked": null,
    "daily_reward_multiplier": 7.0
  },
  {
    "level": 87,
    "xp_to_reach": 191350,
    "xp_from_previous": 4350,
    "title": "Meta Manipulator",
    "unlocks": ["Meta Brush", "Fourth Wall Break Effect", "200 Art Gems"],
    "milestone": false,
    "celebration": "Meta manipulation + wall break",
    "realm_unlocked": null,
    "daily_reward_multiplier": 7.0
  },
  {
    "level": 88,
    "xp_to_reach": 195750,
    "xp_from_previous": 4400,
    "title": "Author of Reality",
    "unlocks": ["Author Brush", "Reality Writing Effect", "Author Color Pack"],
    "milestone": false,
    "celebration": "Reality authorship + writing symphony",
    "realm_unlocked": null,
    "daily_reward_multiplier": 7.0
  },
  {
    "level": 89,
    "xp_to_reach": 200200,
    "xp_from_previous": 4450,
    "title": "The One Above All",
    "unlocks": ["Supreme Authority Brush", "Ultimate Dominion Effect", "205 Art Gems"],
    "milestone": false,
    "celebration": "Supreme authority + ultimate dominion",
    "realm_unlocked": null,
    "daily_reward_multiplier": 7.0
  },
  {
    "level": 90,
    "xp_to_reach": 204700,
    "xp_from_previous": 4500,
    "title": "Eternal Chromatic God",
    "unlocks": ["Godly Chromatic Brush", "Eternal Realm", "Divine Color Mastery Effect", "God Avatar Crown", "Eternal Power-up", "1500 Art Gems"],
    "milestone": true,
    "celebration": "Divine ascension + eternal chromatic symphony",
    "realm_unlocked": "Eternal Realm",
    "daily_reward_multiplier": 8.0
  },
  {
    "level": 91,
    "xp_to_reach": 209250,
    "xp_from_previous": 4550,
    "title": "Boundless Entity",
    "unlocks": ["Boundless Brush", "Limitless Effect", "Boundless Color Pack"],
    "milestone": false,
    "celebration": "Boundless expansion + limitless echo",
    "realm_unlocked": null,
    "daily_reward_multiplier": 8.0
  },
  {
    "level": 92,
    "xp_to_reach": 213850,
    "xp_from_previous": 4600,
    "title": "Incomprehensible Force",
    "unlocks": ["Incomprehensible Brush", "Beyond Understanding Effect", "210 Art Gems"],
    "milestone": false,
    "celebration": "Incomprehensible force + understanding void",
    "realm_unlocked": null,
    "daily_reward_multiplier": 8.0
  },
  {
    "level": 93,
    "xp_to_reach": 218500,
    "xp_from_previous": 4650,
    "title": "Indescribable Being",
    "unlocks": ["Indescribable Brush", "Nameless Effect", "Mystery Color Pack"],
    "milestone": false,
    "celebration": "Indescribable presence + nameless whisper",
    "realm_unlocked": null,
    "daily_reward_multiplier": 8.0
  },
  {
    "level": 94,
    "xp_to_reach": 223200,
    "xp_from_previous": 4700,
    "title": "Unimaginable Power",
    "unlocks": ["Unimaginable Brush", "Beyond Imagination Effect", "215 Art Gems"],
    "milestone": false,
    "celebration": "Unimaginable power + imagination break",
    "realm_unlocked": null,
    "daily_reward_multiplier": 8.0
  },
  {
    "level": 95,
    "xp_to_reach": 227950,
    "xp_from_previous": 4750,
    "title": "The Ineffable One",
    "unlocks": ["Ineffable Brush", "Unspeakable Effect", "Ineffable Color Pack", "Impossible Canvas Shape", "220 Art Gems"],
    "milestone": true,
    "celebration": "Ineffable presence + unspeakable harmony",
    "realm_unlocked": null,
    "daily_reward_multiplier": 9.0
  },
  {
    "level": 96,
    "xp_to_reach": 232750,
    "xp_from_previous": 4800,
    "title": "Beyond All Concepts",
    "unlocks": ["Conceptless Brush", "Beyond Definition Effect", "Conceptless Color Pack"],
    "milestone": false,
    "celebration": "Beyond concepts + definition void",
    "realm_unlocked": null,
    "daily_reward_multiplier": 9.0
  },
  {
    "level": 97,
    "xp_to_reach": 237600,
    "xp_from_previous": 4850,
    "title": "The Absolute",
    "unlocks": ["Absolute Brush", "Pure Existence Effect", "225 Art Gems"],
    "milestone": false,
    "celebration": "Absolute presence + pure existence hum",
    "realm_unlocked": null,
    "daily_reward_multiplier": 9.0
  },
  {
    "level": 98,
    "xp_to_reach": 242500,
    "xp_from_previous": 4900,
    "title": "The Ultimate Truth",
    "unlocks": ["Truth Brush", "Ultimate Reality Effect", "Truth Color Pack"],
    "milestone": false,
    "celebration": "Ultimate truth + reality revelation",
    "realm_unlocked": null,
    "daily_reward_multiplier": 9.0
  },
  {
    "level": 99,
    "xp_to_reach": 247450,
    "xp_from_previous": 4950,
    "title": "The Final Form",
    "unlocks": ["Final Brush", "Completion Effect", "230 Art Gems"],
    "milestone": false,
    "celebration": "Final form + completion resonance",
    "realm_unlocked": null,
    "daily_reward_multiplier": 9.0
  },
  {
    "level": 100,
    "xp_to_reach": 252450,
    "xp_from_previous": 5000,
    "title": "Chromatic Overlord Eternal",
    "unlocks": ["Eternal Chromatic Mastery Brush", "The Origin Realm", "Universe Creation Effect", "Overlord Crown Avatar", "Prestige Unlock", "10000 Art Gems", "Cosmic Glow Theme"],
    "milestone": true,
    "celebration": "Universe creation + eternal chromatic symphony + prestige transformation",
    "realm_unlocked": "The Origin Realm",
    "daily_reward_multiplier": 10.0
  }
]